"""Create Tables

Revision ID: 812048cabaa0
Revises: 
Create Date: 2022-04-17 17:48:28.490729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812048cabaa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('table', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'table')
    # ### end Alembic commands ###
