"""First migration

Revision ID: ee455ee4ec6d
Revises: 
Create Date: 2022-04-10 16:23:06.782720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee455ee4ec6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff', sa.String(), nullable=True))
    op.drop_column('users', 'staff_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'staff')
    # ### end Alembic commands ###
