"""Alter Orders

Revision ID: 6845524dcf0f
Revises: b6235cb21250
Create Date: 2022-04-20 21:58:34.746796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6845524dcf0f'
down_revision = 'b6235cb21250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'note')
    # ### end Alembic commands ###
